version: '3.8'

services:
  backend-devops-project:
    image: backend-devops-project
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - DATABASE_URL=jdbc:mysql://your_mysql_host:3306/your_database?createDatabaseIfNotExist=true
      - DATABASE_USERNAME=your_username
      - DATABASE_PASSWORD=your_password
